
%%%%%%%%%%%%
%% Vehicle%%
%%%%%%%%%%%%
clc
clear
load('ratID3_HPC_veh.mat');
load('ratID4_HPC_veh.mat');
load('ratID9_HPC_veh.mat');
load('ratID201_HPC_veh.mat');
load('ratID203_HPC_veh.mat');
load('ratID206_HPC_veh.mat');
load('ratID210_HPC_veh.mat');
load('ratID211_HPC_veh.mat');
load('ratID213_HPC_veh.mat');

%% concat per event type

%% Ripple - (HPCpyra)
GC_detections_HPCpyra_ripple_veh=[GC_ripple_waveforms_HPCpyra_ratID3;GC_ripple_waveforms_HPCpyra_ratID4;...
    GC_ripple_waveforms_HPCpyra_ratID9;GC_ripple_waveforms_HPCpyra_ratID201;...
    GC_ripple_waveforms_HPCpyra_ratID203;GC_ripple_waveforms_HPCpyra_ratID206;...
    GC_ripple_waveforms_HPCpyra_ratID210;GC_ripple_waveforms_HPCpyra_ratID211;GC_ripple_waveforms_HPCpyra_ratID213];
ripple_grouped_oscil_table_HPCpyra_veh=[ripple_grouped_oscil_table_HPCpyra_ratID3;ripple_grouped_oscil_table_HPCpyra_ratID4;...
    ripple_grouped_oscil_table_HPCpyra_ratID9;ripple_grouped_oscil_table_HPCpyra_ratID201;...
    ripple_grouped_oscil_table_HPCpyra_ratID203;ripple_grouped_oscil_table_HPCpyra_ratID206;...
    ripple_grouped_oscil_table_HPCpyra_ratID210;ripple_grouped_oscil_table_HPCpyra_ratID211;ripple_grouped_oscil_table_HPCpyra_ratID213];

%% SW - (HPCbelo)
GC_detections_HPCbelo_sw_veh=[GC_sw_waveforms_HPCbelo_ratID3;GC_sw_waveforms_HPCbelo_ratID4;...
    GC_sw_waveforms_HPCbelo_ratID9;GC_sw_waveforms_HPCbelo_ratID201;...
    GC_sw_waveforms_HPCbelo_ratID203;GC_sw_waveforms_HPCbelo_ratID206;...
    GC_sw_waveforms_HPCbelo_ratID210;GC_sw_waveforms_HPCbelo_ratID211;GC_sw_waveforms_HPCbelo_ratID213];
sw_grouped_oscil_table_HPCbelo_veh=[sw_grouped_oscil_table_HPCbelo_ratID3;sw_grouped_oscil_table_HPCbelo_ratID4;...
    sw_grouped_oscil_table_HPCbelo_ratID9;sw_grouped_oscil_table_HPCbelo_ratID201;...
    sw_grouped_oscil_table_HPCbelo_ratID203;sw_grouped_oscil_table_HPCbelo_ratID206;...
    sw_grouped_oscil_table_HPCbelo_ratID210;sw_grouped_oscil_table_HPCbelo_ratID211;sw_grouped_oscil_table_HPCbelo_ratID213];


%% SWR - (HPCpyra)
GC_detections_HPCpyra_swr_veh=[GC_swr_waveforms_HPCpyra_ratID3;GC_swr_waveforms_HPCpyra_ratID4;...
    GC_swr_waveforms_HPCpyra_ratID9;GC_swr_waveforms_HPCpyra_ratID201;...
    GC_swr_waveforms_HPCpyra_ratID203;GC_swr_waveforms_HPCpyra_ratID206;...
    GC_swr_waveforms_HPCpyra_ratID210;GC_swr_waveforms_HPCpyra_ratID211;GC_swr_waveforms_HPCpyra_ratID213];
swr_grouped_oscil_table_HPCpyra_veh=[swr_grouped_oscil_table_HPCpyra_ratID3;swr_grouped_oscil_table_HPCpyra_ratID4;...
    swr_grouped_oscil_table_HPCpyra_ratID9;swr_grouped_oscil_table_HPCpyra_ratID201;...
    swr_grouped_oscil_table_HPCpyra_ratID203;swr_grouped_oscil_table_HPCpyra_ratID206;...
    swr_grouped_oscil_table_HPCpyra_ratID210;swr_grouped_oscil_table_HPCpyra_ratID211;swr_grouped_oscil_table_HPCpyra_ratID213];

%% Complex SWR - (HPCpyra)
GC_detections_HPCpyra_complex_swr_veh=[GC_complex_swr_waveforms_HPCpyra_ratID3;GC_complex_swr_waveforms_HPCpyra_ratID4;...
    GC_complex_swr_waveforms_HPCpyra_ratID9;GC_complex_swr_waveforms_HPCpyra_ratID201;...
    GC_complex_swr_waveforms_HPCpyra_ratID203;GC_complex_swr_waveforms_HPCpyra_ratID206;...
    GC_complex_swr_waveforms_HPCpyra_ratID210;GC_complex_swr_waveforms_HPCpyra_ratID211;GC_complex_swr_waveforms_HPCpyra_ratID213];
complex_swr_grouped_oscil_table_HPCpyra_veh=[complex_swr_grouped_oscil_table_HPCpyra_ratID3;complex_swr_grouped_oscil_table_HPCpyra_ratID4;...
    complex_swr_grouped_oscil_table_HPCpyra_ratID9;complex_swr_grouped_oscil_table_HPCpyra_ratID201;...
    complex_swr_grouped_oscil_table_HPCpyra_ratID203;complex_swr_grouped_oscil_table_HPCpyra_ratID206;...
    complex_swr_grouped_oscil_table_HPCpyra_ratID210;complex_swr_grouped_oscil_table_HPCpyra_ratID211;complex_swr_grouped_oscil_table_HPCpyra_ratID213];

clearvars -except GC_detections_HPCpyra_ripple_veh ripple_grouped_oscil_table_HPCpyra_veh...
    GC_detections_HPCbelo_sw_veh sw_grouped_oscil_table_HPCbelo_veh...
    GC_detections_HPCpyra_swr_veh swr_grouped_oscil_table_HPCpyra_veh...
    GC_detections_HPCpyra_complex_swr_veh complex_swr_grouped_oscil_table_HPCpyra_veh

save('detections_HPC_veh','-v7.3')

%%
%%%%%%%
%%CBD%%
%%%%%%%

clc
clear
load('ratID2_HPC_cbd.mat');
load('ratID5_HPC_cbd.mat');
load('ratID10_HPC_cbd.mat');
load('ratID11_HPC_cbd.mat');
load('ratID204_HPC_cbd.mat');
load('ratID205_HPC_cbd.mat');
load('ratID207_HPC_cbd.mat');
load('ratID209_HPC_cbd.mat');
load('ratID212_HPC_cbd.mat');
load('ratID214_HPC_cbd.mat');

%% concat per event type

%% Ripple - (HPCpyra)
GC_detections_HPCpyra_ripple_cbd=[GC_ripple_waveforms_HPCpyra_ratID2;GC_ripple_waveforms_HPCpyra_ratID5;...
    GC_ripple_waveforms_HPCpyra_ratID10;GC_ripple_waveforms_HPCpyra_ratID11;...
    GC_ripple_waveforms_HPCpyra_ratID204;GC_ripple_waveforms_HPCpyra_ratID205;...
    GC_ripple_waveforms_HPCpyra_ratID207;GC_ripple_waveforms_HPCpyra_ratID209;...
    GC_ripple_waveforms_HPCpyra_ratID212;GC_ripple_waveforms_HPCpyra_ratID214];
ripple_grouped_oscil_table_HPCpyra_cbd=[ripple_grouped_oscil_table_HPCpyra_ratID2;ripple_grouped_oscil_table_HPCpyra_ratID5;...
    ripple_grouped_oscil_table_HPCpyra_ratID10;ripple_grouped_oscil_table_HPCpyra_ratID11;...
    ripple_grouped_oscil_table_HPCpyra_ratID204;ripple_grouped_oscil_table_HPCpyra_ratID205;...
    ripple_grouped_oscil_table_HPCpyra_ratID207;ripple_grouped_oscil_table_HPCpyra_ratID209;...
    ripple_grouped_oscil_table_HPCpyra_ratID212;ripple_grouped_oscil_table_HPCpyra_ratID214];

%% SW - (HPCbelo)
GC_detections_HPCbelo_sw_cbd=[GC_sw_waveforms_HPCbelo_ratID2;GC_sw_waveforms_HPCbelo_ratID5;...
    GC_sw_waveforms_HPCbelo_ratID10;GC_sw_waveforms_HPCbelo_ratID11;...
    GC_sw_waveforms_HPCbelo_ratID204;GC_sw_waveforms_HPCbelo_ratID205;...
    GC_sw_waveforms_HPCbelo_ratID207;GC_sw_waveforms_HPCbelo_ratID209;...
    GC_sw_waveforms_HPCbelo_ratID212;GC_sw_waveforms_HPCbelo_ratID214];
sw_grouped_oscil_table_HPCbelo_cbd=[sw_grouped_oscil_table_HPCbelo_ratID2;sw_grouped_oscil_table_HPCbelo_ratID5;...
    sw_grouped_oscil_table_HPCbelo_ratID10;sw_grouped_oscil_table_HPCbelo_ratID11;...
    sw_grouped_oscil_table_HPCbelo_ratID204;sw_grouped_oscil_table_HPCbelo_ratID205;...
    sw_grouped_oscil_table_HPCbelo_ratID207;sw_grouped_oscil_table_HPCbelo_ratID209;...
    sw_grouped_oscil_table_HPCbelo_ratID212;sw_grouped_oscil_table_HPCbelo_ratID214];

%% SWR - (HPCpyra)
GC_detections_HPCpyra_swr_cbd=[GC_swr_waveforms_HPCpyra_ratID2;GC_swr_waveforms_HPCpyra_ratID5;...
    GC_swr_waveforms_HPCpyra_ratID10;GC_swr_waveforms_HPCpyra_ratID11;...
    GC_swr_waveforms_HPCpyra_ratID204;GC_swr_waveforms_HPCpyra_ratID205;...
    GC_swr_waveforms_HPCpyra_ratID207;GC_swr_waveforms_HPCpyra_ratID209;...
    GC_swr_waveforms_HPCpyra_ratID212;GC_swr_waveforms_HPCpyra_ratID214];
swr_grouped_oscil_table_HPCpyra_cbd=[swr_grouped_oscil_table_HPCpyra_ratID2;swr_grouped_oscil_table_HPCpyra_ratID5;...
    swr_grouped_oscil_table_HPCpyra_ratID10;swr_grouped_oscil_table_HPCpyra_ratID11;...
    swr_grouped_oscil_table_HPCpyra_ratID204;swr_grouped_oscil_table_HPCpyra_ratID205;...
    swr_grouped_oscil_table_HPCpyra_ratID207;swr_grouped_oscil_table_HPCpyra_ratID209;...
    swr_grouped_oscil_table_HPCpyra_ratID212;swr_grouped_oscil_table_HPCpyra_ratID214];

%% Complex SWR - (HPCpyra)
GC_detections_HPCpyra_complex_swr_cbd=[GC_complex_swr_waveforms_HPCpyra_ratID2;GC_complex_swr_waveforms_HPCpyra_ratID5;...
    GC_complex_swr_waveforms_HPCpyra_ratID10;GC_complex_swr_waveforms_HPCpyra_ratID11;...
    GC_complex_swr_waveforms_HPCpyra_ratID204;GC_complex_swr_waveforms_HPCpyra_ratID205;...
    GC_complex_swr_waveforms_HPCpyra_ratID207;GC_complex_swr_waveforms_HPCpyra_ratID209;...
    GC_complex_swr_waveforms_HPCpyra_ratID212;GC_complex_swr_waveforms_HPCpyra_ratID214];
complex_swr_grouped_oscil_table_HPCpyra_cbd=[complex_swr_grouped_oscil_table_HPCpyra_ratID2;complex_swr_grouped_oscil_table_HPCpyra_ratID5;...
    complex_swr_grouped_oscil_table_HPCpyra_ratID10;complex_swr_grouped_oscil_table_HPCpyra_ratID11;...
    complex_swr_grouped_oscil_table_HPCpyra_ratID204;complex_swr_grouped_oscil_table_HPCpyra_ratID205;...
    complex_swr_grouped_oscil_table_HPCpyra_ratID207;complex_swr_grouped_oscil_table_HPCpyra_ratID209;...
    complex_swr_grouped_oscil_table_HPCpyra_ratID212;complex_swr_grouped_oscil_table_HPCpyra_ratID214];

clearvars -except GC_detections_HPCpyra_ripple_cbd ripple_grouped_oscil_table_HPCpyra_cbd...
    GC_detections_HPCbelo_sw_cbd sw_grouped_oscil_table_HPCbelo_cbd...
    GC_detections_HPCpyra_swr_cbd swr_grouped_oscil_table_HPCpyra_cbd...
    GC_detections_HPCpyra_complex_swr_cbd complex_swr_grouped_oscil_table_HPCpyra_cbd

save('detections_HPC_cbd','-v7.3')














