%
%% Concat the data per event type (Ripple, SW, SWR, complex SWR).
% 4 sections: PFCshal-Veh, PFCdeep-Veh, PFCshal-CBD, PFCdeep-CBD.

%%%%%%%%%%%%%%%%%%%
%% 1) PFCshal-Veh%%
%%%%%%%%%%%%%%%%%%%
clc
clear

%% First, load the data per section.
load('ratID213_PFCshal_veh.mat')
load('ratID211_PFCshal_veh.mat')
load('ratID210_PFCshal_veh.mat')
load('ratID206_PFCshal_veh.mat')
load('ratID203_PFCshal_veh.mat')
load('ratID201_PFCshal_veh.mat')
load('ratID9_PFCshal_veh.mat')
load('ratID4_PFCshal_veh.mat')
load('ratID3_PFCshal_veh.mat')

%% concat per event type
% sw
GC_detections_PFCshal_sw_veh=[GC_sw_waveforms_PFCshal_ratID3;GC_sw_waveforms_PFCshal_ratID4;...
    GC_sw_waveforms_PFCshal_ratID9;GC_sw_waveforms_PFCshal_ratID201;...
    GC_sw_waveforms_PFCshal_ratID203;GC_sw_waveforms_PFCshal_ratID206;...
    GC_sw_waveforms_PFCshal_ratID210;GC_sw_waveforms_PFCshal_ratID211;GC_sw_waveforms_PFCshal_ratID213];
sw_grouped_oscil_table_PFCshal_veh=[sw_grouped_oscil_table_PFCshal_ratID3;sw_grouped_oscil_table_PFCshal_ratID4;...
    sw_grouped_oscil_table_PFCshal_ratID9;sw_grouped_oscil_table_PFCshal_ratID201;...
    sw_grouped_oscil_table_PFCshal_ratID203;sw_grouped_oscil_table_PFCshal_ratID206;...
    sw_grouped_oscil_table_PFCshal_ratID210;sw_grouped_oscil_table_PFCshal_ratID211;sw_grouped_oscil_table_PFCshal_ratID213];

% ripple
GC_detections_PFCshal_ripple_veh=[GC_ripple_waveforms_PFCshal_ratID3;GC_ripple_waveforms_PFCshal_ratID4;...
    GC_ripple_waveforms_PFCshal_ratID9;GC_ripple_waveforms_PFCshal_ratID201;...
    GC_ripple_waveforms_PFCshal_ratID203;GC_ripple_waveforms_PFCshal_ratID206;...
    GC_ripple_waveforms_PFCshal_ratID210;GC_ripple_waveforms_PFCshal_ratID211;GC_ripple_waveforms_PFCshal_ratID213];
ripple_grouped_oscil_table_PFCshal_veh=[ripple_grouped_oscil_table_PFCshal_ratID3;ripple_grouped_oscil_table_PFCshal_ratID4;...
    ripple_grouped_oscil_table_PFCshal_ratID9;ripple_grouped_oscil_table_PFCshal_ratID201;...
    ripple_grouped_oscil_table_PFCshal_ratID203;ripple_grouped_oscil_table_PFCshal_ratID206;...
    ripple_grouped_oscil_table_PFCshal_ratID210;ripple_grouped_oscil_table_PFCshal_ratID211;ripple_grouped_oscil_table_PFCshal_ratID213];

% swr
GC_detections_PFCshal_swr_veh=[GC_swr_waveforms_PFCshal_ratID3;GC_swr_waveforms_PFCshal_ratID4;...
    GC_swr_waveforms_PFCshal_ratID9;GC_swr_waveforms_PFCshal_ratID201;...
    GC_swr_waveforms_PFCshal_ratID203;GC_swr_waveforms_PFCshal_ratID206;...
    GC_swr_waveforms_PFCshal_ratID210;GC_swr_waveforms_PFCshal_ratID211;GC_swr_waveforms_PFCshal_ratID213];
swr_grouped_oscil_table_PFCshal_veh=[swr_grouped_oscil_table_PFCshal_ratID3;swr_grouped_oscil_table_PFCshal_ratID4;...
    swr_grouped_oscil_table_PFCshal_ratID9;swr_grouped_oscil_table_PFCshal_ratID201;...
    swr_grouped_oscil_table_PFCshal_ratID203;swr_grouped_oscil_table_PFCshal_ratID206;...
    swr_grouped_oscil_table_PFCshal_ratID210;swr_grouped_oscil_table_PFCshal_ratID211;swr_grouped_oscil_table_PFCshal_ratID213];

% complex swr
GC_detections_PFCshal_complex_swr_veh=[GC_complex_swr_waveforms_PFCshal_ratID3;GC_complex_swr_waveforms_PFCshal_ratID4;...
    GC_complex_swr_waveforms_PFCshal_ratID9;GC_complex_swr_waveforms_PFCshal_ratID201;...
    GC_complex_swr_waveforms_PFCshal_ratID203;GC_complex_swr_waveforms_PFCshal_ratID206;...
    GC_complex_swr_waveforms_PFCshal_ratID210;GC_complex_swr_waveforms_PFCshal_ratID211;GC_complex_swr_waveforms_PFCshal_ratID213];
complex_swr_grouped_oscil_table_PFCshal_veh=[complex_swr_grouped_oscil_table_PFCshal_ratID3;complex_swr_grouped_oscil_table_PFCshal_ratID4;...
    complex_swr_grouped_oscil_table_PFCshal_ratID9;complex_swr_grouped_oscil_table_PFCshal_ratID201;...
    complex_swr_grouped_oscil_table_PFCshal_ratID203;complex_swr_grouped_oscil_table_PFCshal_ratID206;...
    complex_swr_grouped_oscil_table_PFCshal_ratID210;complex_swr_grouped_oscil_table_PFCshal_ratID211;complex_swr_grouped_oscil_table_PFCshal_ratID213];


clearvars -except GC_detections_PFCshal_sw_veh sw_grouped_oscil_table_PFCshal_veh...
    GC_detections_PFCshal_ripple_veh ripple_grouped_oscil_table_PFCshal_veh...
    GC_detections_PFCshal_swr_veh swr_grouped_oscil_table_PFCshal_veh...
    GC_detections_PFCshal_complex_swr_veh complex_swr_grouped_oscil_table_PFCshal_veh

save('detections_PFCshal_veh','-v7.3')


%%%%%%%%%%%%%%%%%%%
%% 2) PFCshal-CBD%%
%%%%%%%%%%%%%%%%%%%
clc
clear

%% First, load the data per section.
load('ratID214_PFCshal_cbd.mat')
load('ratID212_PFCshal_cbd.mat')
load('ratID209_PFCshal_cbd.mat')
load('ratID207_PFCshal_cbd.mat')
load('ratID205_PFCshal_cbd.mat')
load('ratID204_PFCshal_cbd.mat')
load('ratID11_PFCshal_cbd.mat')
load('ratID10_PFCshal_cbd.mat')
load('ratID5_PFCshal_cbd.mat')
load('ratID2_PFCshal_cbd.mat')

%% concat per event type
% sw
GC_detections_PFCshal_sw_cbd=[GC_sw_waveforms_PFCshal_ratID2;GC_sw_waveforms_PFCshal_ratID5;...
    GC_sw_waveforms_PFCshal_ratID10;GC_sw_waveforms_PFCshal_ratID11;...
    GC_sw_waveforms_PFCshal_ratID204;GC_sw_waveforms_PFCshal_ratID205;...
    GC_sw_waveforms_PFCshal_ratID207;GC_sw_waveforms_PFCshal_ratID209;...
    GC_sw_waveforms_PFCshal_ratID212;GC_sw_waveforms_PFCshal_ratID214];
sw_grouped_oscil_table_PFCshal_cbd=[sw_grouped_oscil_table_PFCshal_ratID2;sw_grouped_oscil_table_PFCshal_ratID5;...
    sw_grouped_oscil_table_PFCshal_ratID10;sw_grouped_oscil_table_PFCshal_ratID11;...
    sw_grouped_oscil_table_PFCshal_ratID204;sw_grouped_oscil_table_PFCshal_ratID205;...
    sw_grouped_oscil_table_PFCshal_ratID207;sw_grouped_oscil_table_PFCshal_ratID209;...
    sw_grouped_oscil_table_PFCshal_ratID212;sw_grouped_oscil_table_PFCshal_ratID214];

% ripple
GC_detections_PFCshal_ripple_cbd=[GC_ripple_waveforms_PFCshal_ratID2;GC_ripple_waveforms_PFCshal_ratID5;...
    GC_ripple_waveforms_PFCshal_ratID10;GC_ripple_waveforms_PFCshal_ratID11;...
    GC_ripple_waveforms_PFCshal_ratID204;GC_ripple_waveforms_PFCshal_ratID205;...
    GC_ripple_waveforms_PFCshal_ratID207;GC_ripple_waveforms_PFCshal_ratID209;...
    GC_ripple_waveforms_PFCshal_ratID212;GC_ripple_waveforms_PFCshal_ratID214];
ripple_grouped_oscil_table_PFCshal_cbd=[ripple_grouped_oscil_table_PFCshal_ratID2;ripple_grouped_oscil_table_PFCshal_ratID5;...
    ripple_grouped_oscil_table_PFCshal_ratID10;ripple_grouped_oscil_table_PFCshal_ratID11;...
    ripple_grouped_oscil_table_PFCshal_ratID204;ripple_grouped_oscil_table_PFCshal_ratID205;...
    ripple_grouped_oscil_table_PFCshal_ratID207;ripple_grouped_oscil_table_PFCshal_ratID209;...
    ripple_grouped_oscil_table_PFCshal_ratID212;ripple_grouped_oscil_table_PFCshal_ratID214];

% swr
GC_detections_PFCshal_swr_cbd=[GC_swr_waveforms_PFCshal_ratID2;GC_swr_waveforms_PFCshal_ratID5;...
    GC_swr_waveforms_PFCshal_ratID10;GC_swr_waveforms_PFCshal_ratID11;...
    GC_swr_waveforms_PFCshal_ratID204;GC_swr_waveforms_PFCshal_ratID205;...
    GC_swr_waveforms_PFCshal_ratID207;GC_swr_waveforms_PFCshal_ratID209;...
    GC_swr_waveforms_PFCshal_ratID212;GC_swr_waveforms_PFCshal_ratID214];
swr_grouped_oscil_table_PFCshal_cbd=[swr_grouped_oscil_table_PFCshal_ratID2;swr_grouped_oscil_table_PFCshal_ratID5;...
    swr_grouped_oscil_table_PFCshal_ratID10;swr_grouped_oscil_table_PFCshal_ratID11;...
    swr_grouped_oscil_table_PFCshal_ratID204;swr_grouped_oscil_table_PFCshal_ratID205;...
    swr_grouped_oscil_table_PFCshal_ratID207;swr_grouped_oscil_table_PFCshal_ratID209;...
    swr_grouped_oscil_table_PFCshal_ratID212;swr_grouped_oscil_table_PFCshal_ratID214];

% complex swr
GC_detections_PFCshal_complex_complex_swr_cbd=[GC_complex_swr_waveforms_PFCshal_ratID2;GC_complex_swr_waveforms_PFCshal_ratID5;...
    GC_complex_swr_waveforms_PFCshal_ratID10;GC_complex_swr_waveforms_PFCshal_ratID11;...
    GC_complex_swr_waveforms_PFCshal_ratID204;GC_complex_swr_waveforms_PFCshal_ratID205;...
    GC_complex_swr_waveforms_PFCshal_ratID207;GC_complex_swr_waveforms_PFCshal_ratID209;...
    GC_complex_swr_waveforms_PFCshal_ratID212;GC_complex_swr_waveforms_PFCshal_ratID214];
complex_swr_grouped_oscil_table_PFCshal_cbd=[complex_swr_grouped_oscil_table_PFCshal_ratID2;complex_swr_grouped_oscil_table_PFCshal_ratID5;...
    complex_swr_grouped_oscil_table_PFCshal_ratID10;complex_swr_grouped_oscil_table_PFCshal_ratID11;...
    complex_swr_grouped_oscil_table_PFCshal_ratID204;complex_swr_grouped_oscil_table_PFCshal_ratID205;...
    complex_swr_grouped_oscil_table_PFCshal_ratID207;complex_swr_grouped_oscil_table_PFCshal_ratID209;...
    complex_swr_grouped_oscil_table_PFCshal_ratID212;complex_swr_grouped_oscil_table_PFCshal_ratID214];


clearvars -except GC_detections_PFCshal_sw_cbd sw_grouped_oscil_table_PFCshal_cbd...
    GC_detections_PFCshal_ripple_cbd ripple_grouped_oscil_table_PFCshal_cbd...
    GC_detections_PFCshal_swr_cbd swr_grouped_oscil_table_PFCshal_cbd...
    GC_detections_PFCshal_complex_swr_cbd complex_swr_grouped_oscil_table_PFCshal_cbd

save('detections_PFCshal_cbd','-v7.3')


%%%%%%%%%%%%%%%%%%%
%% 3) PFCdeep-Veh%%
%%%%%%%%%%%%%%%%%%%
clc
clear

%% First, load the data per section.
load('ratID213_PFCdeep_veh.mat')
load('ratID211_PFCdeep_veh.mat')
load('ratID210_PFCdeep_veh.mat')
load('ratID206_PFCdeep_veh.mat')
load('ratID203_PFCdeep_veh.mat')
load('ratID201_PFCdeep_veh.mat')
load('ratID9_PFCdeep_veh.mat')
load('ratID4_PFCdeep_veh.mat')
load('ratID3_PFCdeep_veh.mat')


%% concat per event type
% sw
GC_detections_PFCdeep_sw_veh=[GC_sw_waveforms_PFCdeep_ratID3;GC_sw_waveforms_PFCdeep_ratID4;...
    GC_sw_waveforms_PFCdeep_ratID9;GC_sw_waveforms_PFCdeep_ratID201;...
    GC_sw_waveforms_PFCdeep_ratID203;GC_sw_waveforms_PFCdeep_ratID206;...
    GC_sw_waveforms_PFCdeep_ratID210;GC_sw_waveforms_PFCdeep_ratID211;GC_sw_waveforms_PFCdeep_ratID213];
sw_grouped_oscil_table_PFCdeep_veh=[sw_grouped_oscil_table_PFCdeep_ratID3;sw_grouped_oscil_table_PFCdeep_ratID4;...
    sw_grouped_oscil_table_PFCdeep_ratID9;sw_grouped_oscil_table_PFCdeep_ratID201;...
    sw_grouped_oscil_table_PFCdeep_ratID203;sw_grouped_oscil_table_PFCdeep_ratID206;...
    sw_grouped_oscil_table_PFCdeep_ratID210;sw_grouped_oscil_table_PFCdeep_ratID211;sw_grouped_oscil_table_PFCdeep_ratID213];

% ripple
GC_detections_PFCdeep_ripple_veh=[GC_ripple_waveforms_PFCdeep_ratID3;GC_ripple_waveforms_PFCdeep_ratID4;...
    GC_ripple_waveforms_PFCdeep_ratID9;GC_ripple_waveforms_PFCdeep_ratID201;...
    GC_ripple_waveforms_PFCdeep_ratID203;GC_ripple_waveforms_PFCdeep_ratID206;...
    GC_ripple_waveforms_PFCdeep_ratID210;GC_ripple_waveforms_PFCdeep_ratID211;GC_ripple_waveforms_PFCdeep_ratID213];
ripple_grouped_oscil_table_PFCdeep_veh=[ripple_grouped_oscil_table_PFCdeep_ratID3;ripple_grouped_oscil_table_PFCdeep_ratID4;...
    ripple_grouped_oscil_table_PFCdeep_ratID9;ripple_grouped_oscil_table_PFCdeep_ratID201;...
    ripple_grouped_oscil_table_PFCdeep_ratID203;ripple_grouped_oscil_table_PFCdeep_ratID206;...
    ripple_grouped_oscil_table_PFCdeep_ratID210;ripple_grouped_oscil_table_PFCdeep_ratID211;ripple_grouped_oscil_table_PFCdeep_ratID213];

% swr
GC_detections_PFCdeep_swr_veh=[GC_swr_waveforms_PFCdeep_ratID3;GC_swr_waveforms_PFCdeep_ratID4;...
    GC_swr_waveforms_PFCdeep_ratID9;GC_swr_waveforms_PFCdeep_ratID201;...
    GC_swr_waveforms_PFCdeep_ratID203;GC_swr_waveforms_PFCdeep_ratID206;...
    GC_swr_waveforms_PFCdeep_ratID210;GC_swr_waveforms_PFCdeep_ratID211;GC_swr_waveforms_PFCdeep_ratID213];
swr_grouped_oscil_table_PFCdeep_veh=[swr_grouped_oscil_table_PFCdeep_ratID3;swr_grouped_oscil_table_PFCdeep_ratID4;...
    swr_grouped_oscil_table_PFCdeep_ratID9;swr_grouped_oscil_table_PFCdeep_ratID201;...
    swr_grouped_oscil_table_PFCdeep_ratID203;swr_grouped_oscil_table_PFCdeep_ratID206;...
    swr_grouped_oscil_table_PFCdeep_ratID210;swr_grouped_oscil_table_PFCdeep_ratID211;swr_grouped_oscil_table_PFCdeep_ratID213];

% complex swr
GC_detections_PFCdeep_complex_swr_veh=[GC_complex_swr_waveforms_PFCdeep_ratID3;GC_complex_swr_waveforms_PFCdeep_ratID4;...
    GC_complex_swr_waveforms_PFCdeep_ratID9;GC_complex_swr_waveforms_PFCdeep_ratID201;...
    GC_complex_swr_waveforms_PFCdeep_ratID203;GC_complex_swr_waveforms_PFCdeep_ratID206;...
    GC_complex_swr_waveforms_PFCdeep_ratID210;GC_complex_swr_waveforms_PFCdeep_ratID211;GC_complex_swr_waveforms_PFCdeep_ratID213];
complex_swr_grouped_oscil_table_PFCdeep_veh=[complex_swr_grouped_oscil_table_PFCdeep_ratID3;complex_swr_grouped_oscil_table_PFCdeep_ratID4;...
    complex_swr_grouped_oscil_table_PFCdeep_ratID9;complex_swr_grouped_oscil_table_PFCdeep_ratID201;...
    complex_swr_grouped_oscil_table_PFCdeep_ratID203;complex_swr_grouped_oscil_table_PFCdeep_ratID206;...
    complex_swr_grouped_oscil_table_PFCdeep_ratID210;complex_swr_grouped_oscil_table_PFCdeep_ratID211;complex_swr_grouped_oscil_table_PFCdeep_ratID213];


clearvars -except GC_detections_PFCdeep_sw_veh sw_grouped_oscil_table_PFCdeep_veh...
    GC_detections_PFCdeep_ripple_veh ripple_grouped_oscil_table_PFCdeep_veh...
    GC_detections_PFCdeep_swr_veh swr_grouped_oscil_table_PFCdeep_veh...
    GC_detections_PFCdeep_complex_swr_veh complex_swr_grouped_oscil_table_PFCdeep_veh

save('detections_PFCdeep_veh.mat','-v7.3')


%%%%%%%%%%%%%%%%%%%
%% 4) PFCdeep-CBD%%
%%%%%%%%%%%%%%%%%%%
clc
clear

%% First, load the data per section.
load('ratID214_PFCdeep_cbd.mat')
load('ratID212_PFCdeep_cbd.mat')
load('ratID209_PFCdeep_cbd.mat')
load('ratID207_PFCdeep_cbd.mat')
load('ratID205_PFCdeep_cbd.mat')
load('ratID204_PFCdeep_cbd.mat')
load('ratID11_PFCdeep_cbd.mat')
load('ratID10_PFCdeep_cbd.mat')
load('ratID5_PFCdeep_cbd.mat')
load('ratID2_PFCdeep_cbd.mat')

%% concat per event type
% sw
GC_detections_PFCdeep_sw_cbd=[GC_sw_waveforms_PFCdeep_ratID2;GC_sw_waveforms_PFCdeep_ratID5;...
    GC_sw_waveforms_PFCdeep_ratID10;GC_sw_waveforms_PFCdeep_ratID11;...
    GC_sw_waveforms_PFCdeep_ratID204;GC_sw_waveforms_PFCdeep_ratID205;...
    GC_sw_waveforms_PFCdeep_ratID207;GC_sw_waveforms_PFCdeep_ratID209;...
    GC_sw_waveforms_PFCdeep_ratID212;GC_sw_waveforms_PFCdeep_ratID214];
sw_grouped_oscil_table_PFCdeep_cbd=[sw_grouped_oscil_table_PFCdeep_ratID2;sw_grouped_oscil_table_PFCdeep_ratID5;...
    sw_grouped_oscil_table_PFCdeep_ratID10;sw_grouped_oscil_table_PFCdeep_ratID11;...
    sw_grouped_oscil_table_PFCdeep_ratID204;sw_grouped_oscil_table_PFCdeep_ratID205;...
    sw_grouped_oscil_table_PFCdeep_ratID207;sw_grouped_oscil_table_PFCdeep_ratID209;...
    sw_grouped_oscil_table_PFCdeep_ratID212;sw_grouped_oscil_table_PFCdeep_ratID214];

% ripple
GC_detections_PFCdeep_ripple_cbd=[GC_ripple_waveforms_PFCdeep_ratID2;GC_ripple_waveforms_PFCdeep_ratID5;...
    GC_ripple_waveforms_PFCdeep_ratID10;GC_ripple_waveforms_PFCdeep_ratID11;...
    GC_ripple_waveforms_PFCdeep_ratID204;GC_ripple_waveforms_PFCdeep_ratID205;...
    GC_ripple_waveforms_PFCdeep_ratID207;GC_ripple_waveforms_PFCdeep_ratID209;...
    GC_ripple_waveforms_PFCdeep_ratID212;GC_ripple_waveforms_PFCdeep_ratID214];
ripple_grouped_oscil_table_PFCdeep_cbd=[ripple_grouped_oscil_table_PFCdeep_ratID2;ripple_grouped_oscil_table_PFCdeep_ratID5;...
    ripple_grouped_oscil_table_PFCdeep_ratID10;ripple_grouped_oscil_table_PFCdeep_ratID11;...
    ripple_grouped_oscil_table_PFCdeep_ratID204;ripple_grouped_oscil_table_PFCdeep_ratID205;...
    ripple_grouped_oscil_table_PFCdeep_ratID207;ripple_grouped_oscil_table_PFCdeep_ratID209;...
    ripple_grouped_oscil_table_PFCdeep_ratID212;ripple_grouped_oscil_table_PFCdeep_ratID214];

% swr
GC_detections_PFCdeep_swr_cbd=[GC_swr_waveforms_PFCdeep_ratID2;GC_swr_waveforms_PFCdeep_ratID5;...
    GC_swr_waveforms_PFCdeep_ratID10;GC_swr_waveforms_PFCdeep_ratID11;...
    GC_swr_waveforms_PFCdeep_ratID204;GC_swr_waveforms_PFCdeep_ratID205;...
    GC_swr_waveforms_PFCdeep_ratID207;GC_swr_waveforms_PFCdeep_ratID209;...
    GC_swr_waveforms_PFCdeep_ratID212;GC_swr_waveforms_PFCdeep_ratID214];
swr_grouped_oscil_table_PFCdeep_cbd=[swr_grouped_oscil_table_PFCdeep_ratID2;swr_grouped_oscil_table_PFCdeep_ratID5;...
    swr_grouped_oscil_table_PFCdeep_ratID10;swr_grouped_oscil_table_PFCdeep_ratID11;...
    swr_grouped_oscil_table_PFCdeep_ratID204;swr_grouped_oscil_table_PFCdeep_ratID205;...
    swr_grouped_oscil_table_PFCdeep_ratID207;swr_grouped_oscil_table_PFCdeep_ratID209;...
    swr_grouped_oscil_table_PFCdeep_ratID212;swr_grouped_oscil_table_PFCdeep_ratID214];

% complex swr
GC_detections_PFCdeep_complex_swr_cbd=[GC_complex_swr_waveforms_PFCdeep_ratID2;GC_complex_swr_waveforms_PFCdeep_ratID5;...
    GC_complex_swr_waveforms_PFCdeep_ratID10;GC_complex_swr_waveforms_PFCdeep_ratID11;...
    GC_complex_swr_waveforms_PFCdeep_ratID204;GC_complex_swr_waveforms_PFCdeep_ratID205;...
    GC_complex_swr_waveforms_PFCdeep_ratID207;GC_complex_swr_waveforms_PFCdeep_ratID209;...
    GC_complex_swr_waveforms_PFCdeep_ratID212;GC_complex_swr_waveforms_PFCdeep_ratID214];
complex_swr_grouped_oscil_table_PFCdeep_cbd=[complex_swr_grouped_oscil_table_PFCdeep_ratID2;complex_swr_grouped_oscil_table_PFCdeep_ratID5;...
    complex_swr_grouped_oscil_table_PFCdeep_ratID10;complex_swr_grouped_oscil_table_PFCdeep_ratID11;...
    complex_swr_grouped_oscil_table_PFCdeep_ratID204;complex_swr_grouped_oscil_table_PFCdeep_ratID205;...
    complex_swr_grouped_oscil_table_PFCdeep_ratID207;complex_swr_grouped_oscil_table_PFCdeep_ratID209;...
    complex_swr_grouped_oscil_table_PFCdeep_ratID212;complex_swr_grouped_oscil_table_PFCdeep_ratID214];


clearvars -except GC_detections_PFCdeep_sw_cbd sw_grouped_oscil_table_PFCdeep_cbd...
    GC_detections_PFCdeep_ripple_cbd ripple_grouped_oscil_table_PFCdeep_cbd...
    GC_detections_PFCdeep_swr_cbd swr_grouped_oscil_table_PFCdeep_cbd...
    GC_detections_PFCdeep_complex_swr_cbd complex_swr_grouped_oscil_table_PFCdeep_cbd

save('detections_PFCdeep_cbd','-v7.3')




