
%% Combine the data per treatment % short vs long

%%%%%%%%%%%%%
%% VEHICLE %%
%%%%%%%%%%%%%
clear
cd C:\Users\students\Desktop\Pelin\slope-analysis\data_chronics\Vehicle

%% manually load all files

%% Short Ripples
short_ripples_chronics= [rat6_SD5_posttrial54_short;...
rat6_SD5_posttrial53_short;...
rat6_SD5_posttrial52_short;... 
rat6_SD5_posttrial51_short;...
rat6_SD5_posttrial4_short;...
rat6_SD5_posttrial3_short;...
rat6_SD5_posttrial2_short;...
rat6_SD5_posttrial1_short;...
rat6_SD4_presleep_short;...
rat6_SD4_posttrial52_short;...
rat6_SD4_posttrial51_short;...
rat6_SD4_posttrial4_short;...
rat6_SD4_posttrial3_short;...
rat6_SD4_posttrial2_short;...
rat6_SD4_posttrial1_short;...
rat6_SD1_posttrial54_short;...
rat6_SD1_posttrial53_short;...
rat6_SD1_posttrial52_short;...
rat6_SD1_posttrial51_short;...
rat6_SD1_posttrial4_short;...
rat6_SD1_posttrial3_short;...
rat6_SD1_posttrial2_short;...
rat6_SD1_posttrial1_short;...
rat5_SD4_posttrial4_short;...
rat5_SD4_posttrial3_short;...
rat5_SD4_posttrial2_short;...
rat5_SD4_posttrial1_short;...
rat5_SD4_posttria54_short;...
rat5_SD4_posttria53_short;...
rat5_SD4_posttria52_short;...
rat5_SD4_posttria51_short;...
rat5_SD3_posttrial52_short;... 
rat5_SD3_posttrial51_short;...
rat5_SD3_posttrial4_short;...
rat5_SD3_posttrial3_short;...
rat5_SD3_posttrial2_short;...
rat5_SD2_posttrial4_short;...
rat5_SD2_posttrial3_short;...
rat5_SD2_posttrial2_short;...
rat5_SD2_posttrial1_short;...
rat4_SD6_posttrial54_short;...
rat4_SD6_posttrial53_short;...
rat4_SD6_posttrial52_short;...
rat4_SD6_posttrial51_short;...
rat4_SD6_posttrial4_short;...
rat4_SD6_posttrial3_short;...
rat4_SD6_posttrial2_short;...
rat4_SD2_posttrial54_short;...
rat4_SD2_posttrial52_short;...
rat4_SD2_posttrial51_short;...
rat4_SD2_posttrial3_short;...
rat4_SD2_posttrial2_short;...
rat4_SD2_posttrial1_short;...
rat4_SD1_posttrial54_short;... 
rat4_SD1_posttrial53_short;...
rat4_SD1_posttrial52_short;...
rat4_SD1_posttrial51_short;...
rat4_SD1_posttrial4_short;...
rat4_SD1_posttrial3_short;...
rat4_SD1_posttrial2_short];

%% Long Ripples
long_ripples_chronics=[...
rat6_SD5_posttrial54_long;...
rat6_SD5_posttrial53_long;...
rat6_SD5_posttrial52_long;...
rat6_SD5_posttrial51_long;...
rat6_SD5_posttrial4_long;...
rat6_SD5_posttrial3_long;...
rat6_SD5_posttrial2_long;...
rat6_SD5_posttrial1_long;...
rat6_SD4_presleep_long;...
rat6_SD4_posttrial52_long;...
rat6_SD4_posttrial51_long;...
rat6_SD4_posttrial4_long;...
rat6_SD4_posttrial3_long;...
rat6_SD4_posttrial2_long;...
rat6_SD4_posttrial1_long;...
rat6_SD1_posttrial54_long;... 
rat6_SD1_posttrial53_long;...
rat6_SD1_posttrial52_long;...
rat6_SD1_posttrial51_long;...
rat6_SD1_posttrial4_long;...
rat6_SD1_posttrial3_long;...
rat5_SD4_posttrial54_long;...
rat5_SD4_posttrial53_long;...
rat5_SD4_posttrial52_long;...
rat5_SD4_posttrial51_long;...
rat5_SD4_posttrial4_long;...
rat5_SD4_posttrial3_long;...
rat5_SD4_posttrial2_long;...
rat5_SD4_posttrial1_long;...
rat5_SD3_posttrial52_long;...
rat5_SD3_posttrial51_long;...
rat5_SD3_posttrial4_long;...
rat5_SD3_posttrial3_long;...
rat5_SD3_posttrial2_long;...
rat5_SD2_posttrial51_long;...
rat5_SD2_posttrial4_long;...
rat5_SD2_posttrial3_long;...
rat5_SD2_posttrial2_long;...
rat5_SD2_posttrial1_long;...
rat4_SD6_posttrial54_long;...
rat4_SD6_posttrial52_long;...
rat4_SD6_posttrial51_long;...
rat4_SD6_posttrial4_long;...
rat4_SD6_posttrial3_long;...
rat4_SD6_posttrial2_long;...
rat4_SD2_posttrial51_long;...
rat4_SD2_posttrial2_long;...
rat4_SD2_posttrial1_long;...
rat4_SD1_posttrial53_long;...
rat4_SD1_posttrial52_long;...
rat4_SD1_posttrial51_long;...
rat4_SD1_posttrial4_long;...
rat4_SD1_posttrial3_long];

clearvars -except -regexp chronics
cd C:\Users\students\Desktop\Pelin\slope-analysis\data_chronics

data_info='1-> PFC; 2-> HPC';
short_ripples_chronics_veh=short_ripples_chronics;
save short_ripples_chronics_veh.mat short_ripples_chronics_veh data_info -v7.3
long_ripples_chronics_veh=long_ripples_chronics;
save long_ripples_chronics_veh.mat long_ripples_chronics_veh data_info -v7.3

%%%%%%%%%
%% CBD %%
%%%%%%%%%
clear
cd C:\Users\students\Desktop\Pelin\slope-analysis\data_chronics\CBD

%% manually load all files

%% Short Ripples
short_ripples_chronics_cbd=[...
rat6_SD6_posttrial54_short;...
rat6_SD6_posttrial53_short;...
rat6_SD6_posttrial52_short;...
rat6_SD6_posttrial51_short;...
rat6_SD6_posttrial4_short;...
rat6_SD6_posttrial3_short;...
rat6_SD6_posttrial2_short;...
rat6_SD6_posttrial1_short;...
rat6_SD3_presleep_short;...
rat6_SD3_posttrial54_short;...
rat6_SD3_posttrial53_short;...
rat6_SD3_posttrial52_short;...
rat6_SD3_posttrial51_short;...
rat6_SD3_posttrial4_short;...
rat6_SD3_posttrial3_short;...
rat6_SD3_posttrial2_short;...
rat6_SD3_posttrial1_short;...
rat6_SD2_posttrial54_short;...
rat6_SD2_posttrial53_short;...
rat6_SD2_posttrial52_short;...
rat6_SD2_posttrial51_short;...
rat6_SD2_posttrial4_short;...
rat6_SD2_posttrial3_short;...
rat6_SD2_posttrial2_short;...
rat6_SD2_posttrial1_short;...
rat5_SD6_presleep_short;...
rat5_SD6_posttrial54_short;...
rat5_SD6_posttrial53_short;...
rat5_SD6_posttrial52_short;...
rat5_SD6_posttrial51_short;...
rat5_SD6_posttrial4_short;...
rat5_SD6_posttrial3_short;...
rat5_SD6_posttrial2_short;...
rat5_SD6_posttrial1_short;...
rat5_SD5_presleep_short;...
rat5_SD5_posttrial54_short;...
rat5_SD5_posttrial53_short;...
rat5_SD5_posttrial52_short;...
rat5_SD5_posttrial51_short;...
rat5_SD5_posttrial4_short;...
rat5_SD5_posttrial3_short;...
rat5_SD5_posttrial2_short;...
rat5_SD5_posttrial1_short;...
rat5_SD1_posttrial53_short;...
rat5_SD1_posttrial51_short;...
rat5_SD1_posttrial4_short;...
rat5_SD1_posttrial3_short;...
rat5_SD1_posttrial2_short;...
rat5_SD1_posttrial1_short;...
rat4_SD7_posttrial54_short;...
rat4_SD7_posttrial53_short;...
rat4_SD7_posttrial52_short;...
rat4_SD7_posttrial51_short;...
rat4_SD7_posttrial4_short;...
rat4_SD7_posttrial2_short;...
rat4_SD7_posttrial1_short;...
rat4_SD4_presleep_short;...
rat4_SD4_posttrial53_short;...
rat4_SD4_posttrial52_short;...
rat4_SD4_posttrial51_short;...
rat4_SD4_posttrial4_short;... 
rat4_SD4_posttrial3_short;... 
rat4_SD4_posttrial2_short;... 
rat4_SD3_presleep_short;...
rat4_SD3_posttrial54_short;...
rat4_SD3_posttrial53_short;...
rat4_SD3_posttrial52_short;...
rat4_SD3_posttrial51_short;...
rat4_SD3_posttrial4_short;...
rat4_SD3_posttrial3_short;...
rat4_SD3_posttrial2_short;...
rat4_SD3_posttrial1_short];




%% Long Ripples
long_ripples_chronics_cbd=[...
rat6_SD6_posttrial54_long;...
rat6_SD6_posttrial53_long;...
rat6_SD6_posttrial51_long;...
rat6_SD6_posttrial4_long;...
rat6_SD6_posttrial3_long;
rat6_SD6_posttrial2_long;
rat6_SD3_presleep_long;
rat6_SD3_posttrial54_long;
rat6_SD3_posttrial53_long;
rat6_SD3_posttrial52_long;
rat6_SD3_posttrial51_long;
rat6_SD3_posttrial4_long; 
rat6_SD3_posttrial3_long;
rat6_SD3_posttrial2_long;
rat6_SD3_posttrial1_long;
rat6_SD2_posttrial54_long;
rat6_SD2_posttrial53_long;
rat6_SD2_posttrial52_long;
rat6_SD2_posttrial51_long;
rat6_SD2_posttrial4_long;
rat6_SD2_posttrial3_long;
rat6_SD2_posttrial2_long;
rat6_SD2_posttrial1_long;
rat5_SD6_presleep_long;
rat5_SD6_posttrial54_long;
rat5_SD6_posttrial53_long;
rat5_SD6_posttrial52_long; 
rat5_SD6_posttrial4_long;
rat5_SD6_posttrial3_long;
rat5_SD6_posttrial2_long;
rat5_SD5_presleep_long;
rat5_SD5_posttrial54_long;
rat5_SD5_posttrial53_long;
rat5_SD5_posttrial52_long;
rat5_SD5_posttrial51_long; 
rat5_SD5_posttrial4_long;
rat5_SD5_posttrial3_long;
rat5_SD5_posttrial2_long; 
rat5_SD5_posttrial1_long; 
rat5_SD1_posttrial53_long; 
rat5_SD1_posttrial4_long; 
rat5_SD1_posttrial3_long;
rat5_SD1_posttrial2_long;
rat5_SD1_posttrial1_long;
rat4_SD7_posttrial52_long; 
rat4_SD7_posttrial4_long;
rat4_SD7_posttrial2_long; 
rat4_SD4_presleep_long;
rat4_SD4_posttrial53_long;
rat4_SD4_posttrial52_long;
rat4_SD4_posttrial51_long;
rat4_SD4_posttrial4_long;
rat4_SD4_posttrial3_long;
rat4_SD3_presleep_long;
rat4_SD3_posttrial54_long; 
rat4_SD3_posttrial53_long;
rat4_SD3_posttrial52_long;
rat4_SD3_posttrial51_long; 
rat4_SD3_posttrial4_long;
rat4_SD3_posttrial3_long;
rat4_SD3_posttrial1_long];


clearvars -except -regexp chronics
cd C:\Users\students\Desktop\Pelin\slope-analysis\data_chronics

data_info='1-> PFC; 2-> HPC';
save short_ripples_chronics_cbd.mat short_ripples_chronics_cbd data_info -v7.3
save long_ripples_chronics_cbd.mat long_ripples_chronics_cbd data_info -v7.3


